In [1]:
import torch

In [2]:
torch.tensor([[1.,-1.],[1.,-1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [3]:
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]],device="cuda:0"))
print(torch.tensor([[1,2],[3,4]],dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0],temp[1],temp[-1])
print(temp[2:5],temp[4:-1])

v = torch.tensor([1,2,3])
w = torch.tensor([3,5,6])
print(w-v)

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])
tensor([2, 3, 3])


In [6]:
temp = torch.tensor([[1,2],[3,4]])

In [7]:
print(temp.shape)

torch.Size([2, 2])


In [8]:
print(temp.view(4,1))

tensor([[1],
        [2],
        [3],
        [4]])


In [10]:
print(temp.view(-1))

tensor([1, 2, 3, 4])


In [11]:
print(temp.view(1,-1))

tensor([[1, 2, 3, 4]])


In [13]:
temp.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [17]:
import torch
import numpy as np

In [18]:
x = torch.empty(5,4)
print(x)

tensor([[2.3859e-35, 3.5039e-41, 2.3890e-35, 3.5039e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.1084e-44, 0.0000e+00],
        [2.3109e+05, 4.0350e-41, 2.3982e-35, 3.5039e-41]])


In [19]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
torch.zeros(2)

tensor([0., 0.])

In [21]:
torch.empty(4,5)

tensor([[2.8200e-35, 3.5039e-41, 8.7698e-37, 3.5039e-41, 2.5202e-14],
        [4.0349e-41, 1.4013e-45, 0.0000e+00, 1.2612e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [22]:
torch.rand(5,6)

tensor([[0.6952, 0.8356, 0.5566, 0.8803, 0.4258, 0.0389],
        [0.2731, 0.8602, 0.8389, 0.0272, 0.2579, 0.3734],
        [0.2271, 0.2692, 0.6164, 0.6710, 0.9257, 0.0634],
        [0.6377, 0.0022, 0.5557, 0.5004, 0.0090, 0.9735],
        [0.8952, 0.5394, 0.0782, 0.3386, 0.6993, 0.2146]])

In [23]:
# 리스트, 넘파이 배열 텐서로 만들기

In [24]:
l = [13,4]
r = np.array([4,56,7])

In [25]:
torch.tensor(l)

tensor([13,  4])

In [26]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [30]:
x.size()[1]

4

In [31]:
x.size()[0]

5

In [32]:
torch.Size([5,4])

torch.Size([5, 4])

In [35]:
x=torch.rand(2,2)
y = torch.rand(2,2)

In [36]:
x+y

tensor([[0.6753, 1.3394],
        [0.5745, 1.5522]])

In [41]:
torch.add(x,y)

tensor([[0.6753, 1.3394],
        [0.5745, 1.5522]])

In [42]:
y.add(x)

tensor([[0.6753, 1.3394],
        [0.5745, 1.5522]])

In [43]:
x = torch.rand(8,8)

In [44]:
x

tensor([[0.2952, 0.1500, 0.0289, 0.5882, 0.1468, 0.2930, 0.8482, 0.8857],
        [0.4661, 0.9988, 0.3631, 0.2055, 0.8848, 0.4126, 0.1119, 0.1512],
        [0.0315, 0.1843, 0.4193, 0.0643, 0.9844, 0.6310, 0.3121, 0.3101],
        [0.5980, 0.9241, 0.9588, 0.2604, 0.8417, 0.1370, 0.6708, 0.3729],
        [0.3380, 0.6101, 0.0213, 0.7661, 0.2035, 0.3447, 0.0041, 0.0269],
        [0.9243, 0.1450, 0.0205, 0.7775, 0.3270, 0.0541, 0.2296, 0.9604],
        [0.1649, 0.6320, 0.3907, 0.9078, 0.4777, 0.4693, 0.5293, 0.3569],
        [0.8985, 0.4134, 0.0156, 0.4803, 0.7218, 0.0914, 0.8377, 0.0799]])

In [47]:
x.shape

torch.Size([8, 8])

In [49]:
x.view(-1,8,4)

tensor([[[0.2952, 0.1500, 0.0289, 0.5882],
         [0.1468, 0.2930, 0.8482, 0.8857],
         [0.4661, 0.9988, 0.3631, 0.2055],
         [0.8848, 0.4126, 0.1119, 0.1512],
         [0.0315, 0.1843, 0.4193, 0.0643],
         [0.9844, 0.6310, 0.3121, 0.3101],
         [0.5980, 0.9241, 0.9588, 0.2604],
         [0.8417, 0.1370, 0.6708, 0.3729]],

        [[0.3380, 0.6101, 0.0213, 0.7661],
         [0.2035, 0.3447, 0.0041, 0.0269],
         [0.9243, 0.1450, 0.0205, 0.7775],
         [0.3270, 0.0541, 0.2296, 0.9604],
         [0.1649, 0.6320, 0.3907, 0.9078],
         [0.4777, 0.4693, 0.5293, 0.3569],
         [0.8985, 0.4134, 0.0156, 0.4803],
         [0.7218, 0.0914, 0.8377, 0.0799]]])

In [50]:
x = torch.rand(8,8)

In [51]:
y = x.numpy()

In [52]:
y

array([[0.12149656, 0.82172984, 0.62879777, 0.30094653, 0.5065537 ,
        0.50566363, 0.34697205, 0.15131581],
       [0.1004473 , 0.8866577 , 0.1808232 , 0.78595835, 0.9586305 ,
        0.7332472 , 0.64517826, 0.999548  ],
       [0.9434946 , 0.15556246, 0.6272476 , 0.4505452 , 0.83384883,
        0.9645692 , 0.0169245 , 0.61114603],
       [0.38851744, 0.57220745, 0.30028903, 0.3994931 , 0.37484634,
        0.9628441 , 0.86905444, 0.81812507],
       [0.33303672, 0.32029969, 0.84454495, 0.6395044 , 0.37624878,
        0.26913267, 0.28835005, 0.6818458 ],
       [0.541328  , 0.10494167, 0.33255768, 0.25623196, 0.9280872 ,
        0.6498191 , 0.20054203, 0.09909147],
       [0.12376755, 0.8280068 , 0.71976495, 0.00234258, 0.6831234 ,
        0.06525528, 0.24757642, 0.94663084],
       [0.4925902 , 0.9646753 , 0.8883604 , 0.77451354, 0.517407  ,
        0.46085024, 0.97691905, 0.42107594]], dtype=float32)

In [53]:
type(y)

numpy.ndarray

In [54]:
x = torch.ones(1)
x

tensor([1.])

In [56]:
print(x.item()) # pandas values 랑 똑같음

1.0


In [57]:
# 텐서 조작하기

In [58]:
t = np.array([[[0,1,2],
               [3,4,5]],
               [[6,7,8],
                [9,10,11]]])

In [59]:
r = torch.FloatTensor(t)
r

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [60]:
r.shape

torch.Size([2, 2, 3])

In [75]:
r.view(-1,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [80]:
# 스퀴즈 - n차원이 1인 경우 해당 차원을 제거한다
r.view(1,2,6).squeeze().shape

torch.Size([2, 6])

In [103]:
print(r.view(1,2,6).squeeze().unsqueeze(0).shape)
print(r.view(1,2,6).squeeze().unsqueeze(1).shape)
print(r.view(1,2,6).squeeze().unsqueeze(2).shape)

torch.Size([1, 2, 6])
torch.Size([2, 1, 6])
torch.Size([2, 6, 1])


In [ ]:
# 언스퀴즈는 위치에 따른 1 차원을 늘려준다. (un)

In [87]:
ft = torch.Tensor([0,1,2])
ft.shape

torch.Size([3])

In [98]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [ ]:
# 타입 캐스팅
# 32비트 torch.FloatTensor
# 64비트 torch.LongTensor
# GPU torch.cuda.FloatTenosr

In [105]:
x  = torch.LongTensor([1,2,3,4])
print(x)

tensor([1, 2, 3, 4])


In [106]:
x  = torch.FloatTensor([1,2,3,4])

In [108]:
bt = torch.ByteTensor([True,True,False,False])
bt

tensor([1, 1, 0, 0], dtype=torch.uint8)